/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicForm;

/**
 *
 * @author My computer
 */
import java.util.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
public class ToaThuoc extends javax.swing.JFrame {
    
    String[] Thoigian = {"S","Tr","C","T","S+Tr","S+C","S+T","Tr+C","Tr+T","C+T"
                        ,"S+Tr+C+T","Sau khi ăn","Trước khi ăn"};
    String[] Cachdung = {"Uống","Ngậm","Chích","Bơm"};
    
    ArrayList<String> toa = new ArrayList();
    static String DB_Son_Akat = "jdbc:mysql://192.168.43.235:3306/akat";
    static String DB_Son_Hackathon = "jdbc:mysql://172.16.3.17:3306/akat";
    static String DB_Chi = "jdbc:mysql://192.168.43.203:3306/mydb";
    //String DB_Chi = "jdbc:mysql://172.16.3.24:3306/quanlygiaovu";
    static final String USER = "root";
    static final String PASS = "123456";
    static Connection conn = null;
    static Statement stmt = null;
    static ResultSet rs;
    static PreparedStatement pstmt = null;
    private String sql = "SELECT * FROM thuoc";
    /**
     * Creates new form ToaThuoc
     */
    static JFrame ToaThuocF;
    int i=2;
    Object[] row = new Object[6];
    
    public ToaThuoc() {
        initComponents();
        super.setLocationRelativeTo(null);
        try{
            conn = DriverManager.getConnection(DB_Son_Hackathon,USER,PASS);
            pstmt = conn.prepareStatement(sql);
            rs = pstmt.executeQuery();
            
            while(rs.next())
            {
                toa.add(rs.getString("TENTHUOC"));
            }
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        JComboBox CbThoiGian = new JComboBox(Thoigian);
        JComboBox CbCachdung = new JComboBox(Cachdung);
        JComboBox CbThuoc = new JComboBox(toa.toArray());
        JtToaThuoc.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(CbThoiGian));
        JtToaThuoc.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(CbCachdung));
        JtToaThuoc.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(CbThuoc));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JtToaThuoc = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BtThem = new javax.swing.JButton();
        BtXoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Toa thuốc");
        setAlwaysOnTop(true);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        JtToaThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Tên thuốc", "Số lượng bán", "Cách dùng", "Thời gian", "Liều lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JtToaThuoc.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(JtToaThuoc);
        if (JtToaThuoc.getColumnModel().getColumnCount() > 0) {
            JtToaThuoc.getColumnModel().getColumn(0).setResizable(false);
            JtToaThuoc.getColumnModel().getColumn(0).setPreferredWidth(200);
            JtToaThuoc.getColumnModel().getColumn(1).setResizable(false);
            JtToaThuoc.getColumnModel().getColumn(1).setPreferredWidth(45);
            JtToaThuoc.getColumnModel().getColumn(2).setResizable(false);
            JtToaThuoc.getColumnModel().getColumn(2).setPreferredWidth(40);
            JtToaThuoc.getColumnModel().getColumn(3).setResizable(false);
            JtToaThuoc.getColumnModel().getColumn(3).setPreferredWidth(35);
            JtToaThuoc.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Lưu");

        BtThem.setText("Thêm");
        BtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtThemActionPerformed(evt);
            }
        });

        BtXoa.setText("Xóa");
        BtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtXoaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời gian"));

        jLabel1.setText("S : Sáng");

        jLabel2.setText("Tr : Trưa");

        jLabel3.setText("C : Chiều");

        jLabel4.setText("T : Tối");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtThemActionPerformed
        DefaultTableModel model = (DefaultTableModel)JtToaThuoc.getModel();
        model.addRow(row);
    }//GEN-LAST:event_BtThemActionPerformed

    private void BtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtXoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)JtToaThuoc.getModel();
        if (JtToaThuoc.getSelectedRow()!= -1)
        {
            model.removeRow(JtToaThuoc.getSelectedRow());
        }
    }//GEN-LAST:event_BtXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String[] args)
    //{
        //ToaThuocF = new ToaThuoc();
        //ToaThuocF.setVisible(true);
    //}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtThem;
    private javax.swing.JButton BtXoa;
    private javax.swing.JTable JtToaThuoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
